const RECRUITMENT_OPEN: boolean = false;

const DESIGNER_FORM_URL: string = "";

const DEVELOPER_FORM_URL: string = "";

const IMPACT_STATS: {
 NPOS_SERVED: number;
 HOURS_VOLUNTEERED: number;
} = {
 NPOS_SERVED: 17,
 HOURS_VOLUNTEERED: 2000,
};

const SCHOOL_YEAR_START: string = "2025";

const SCHOOL_YEAR_END: string = "2026";

export {
 RECRUITMENT_OPEN,
 SCHOOL_YEAR_START,
 SCHOOL_YEAR_END,
 IMPACT_STATS,
 DESIGNER_FORM_URL,
 DEVELOPER_FORM_URL,
};
